Fix for test_resolve_entrypoints_duplicate_name
This test checks that some warning is logged when multiple entry points are found for one module. However, this part of the code is never reached if on the second call with reuse_cached_imports = True instead of False. That is because the entrypoints are cached in the previous call, which skips  _load_from_entrypoints where the warning is raised.

Therefore ymmsl_cache is cleared before and after each test to ensure a clean slate.

The failed test::
FAILED ymmsl/v0_2/tests/test_resolver.py::test_resolve_entrypoints_duplicate_name[True] - assert 0 == 1
 +  where 0 = len([])